	CREATE DATABASE CRUN_N_CAPAS
	USE CRUN_N_CAPAS
	
	CREATE TABLE Personas (
	ID INT PRIMARY KEY,
	Nombre NVARCHAR (30),
	Apellido NVARCHAR (30),
	Sexo NVARCHAR (12)
	);
	
	SELECT * FROM Personas;
